[workspace]
name = "freecad.frametools"
version = "0.1.0"
description = "Frame workbench for FreeCAD"
authors = ["looooo <sppedflyer@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
requires-pixi = ">=0.48"

[dependencies]
freecad = "*"
scipy = "*"
fonts-conda-forge = "*"

[pypi-dependencies]
"freecad.frametools" = { path = ".", editable = true }

[tasks]
tests = "freecadcmd tests/run_tests.py"
reset-font-cache = "bash -c 'rm -rf \"$CONDA_PREFIX/var/cache/fontconfig/\"/* && fc-cache -fv'"